### PR TITLE
fix: remove api container stuff & colorize keys

### LINKED ISSUE #185: [FR]: remove all "API container" fields in `enclave inspect` output (including the result of `kurtosis run`)
### Background and motivation

The quickstart user experience testers got confused by this, and it's not useful or necessary for users, plus pollutes the `enclave inspect` output.

### Current behavior

All the "API Container" rows get printed

### Desired behavior

All these rows in `enclave inspect` output are removed

### How important is this feature or improvement to you?

Nice to have, this feature would make using Kurtosis more enjoyable.

### PR DESCRIPTION
**Pull request by h4ck3rk3y**
## Description:
We remove APIC status from enclave inspect and also make keys bold

## Is this change user facing?

* [x] Yes
* [ ] No

## References (if applicable):
https://github.com/kurtosis-tech/kurtosis/issues/185

### CODE REVIEW

**Comment by h4ck3rk3y** [comment]
image

**Review by Peeeekay — APPROVED** [review]

**Comment by mieubrisse** [comment]
1) can we do the same treatment to the service table heades?

**Comment by mieubrisse** [comment]
2. If it's supereasy, can we correct the enclave metadata section like so:
```
Name:
UUID
Status
Creation Time
```
(dropping "Enclave" where possible, and putting Name [most salient info] first)

**Review by mieubrisse — APPROVED** [review]

**Comment by h4ck3rk3y** [comment]
image

**Pull request merged**
