### PR TITLE
feat: Always keep latest released version of Kurtosis images

### PR DESCRIPTION
**Pull request by victorcolombo**
## Description:

Before this PR, images were deleted based on if they were being used by any container and were not dev versions. This caused the latest released version to be deleted if there were no enclaves active.

After this PR, the algorithm is:
- Keep all dev versions
- Keep the latest released version
- Keep all images that are used by at least one container

## Is this change user facing?
YES

## References (if applicable):

https://github.com/kurtosis-tech/kurtosis/issues/1457

### CODE REVIEW

**Comment by mieubrisse** [comment]
When you say, "keep latest released version" does that mean "keep the version of the CLI being currently run?" As written, it sounds like if the latest is 1.2.3. and I downgrade my CLI to 1.2.0, then the CLI will continually be deleting the images of 1.2.0

I'd been under the impression that the algorithm we'd discussed a while back was:

- Keep all dev versions (so you're not getting dev versions yanked out from under you)
- Keep all versions >= the version of the CLI doing the `clean` (so you're not deleting future versions, in case you've downgraded)
- Keep all images that are used by at least one container (so that we're not erroring)

This is the algorithm that makes the most sense to me as a user, though I could be convinced that point #2 should be "keep all versions == the version of the CLI doing the `clean`" so that if you downgrade, you're not left with future versions (you may never intend to reupgrade).

**Comment by h4ck3rk3y** [comment]
Assigning the review to @mieubrisse as he's already on it!

**Comment by victorcolombo** [comment]
That makes sense @mieubrisse, bullets 1 and 3 are already covered, now there are two viable options for 2:

1. Keep only images where version == CLI (This is the current behavior on this PR, and the one I find most intuitive). The current use case for `clean -a` for users is to minimize Kurtosis footprint to a minimum, keeping only what is absolutely necessary to run. In this case, the intuitive behavior for a user in my opinion is that, if you pinned a version by downgrading it on your cluster, you should only keep the version you actually need to run.
2. Keep images >= CLI (Behavior you are suggesting). This case is more aligned with what a Kurtosis dev would face (downgrading and upgrading Kurtosis to bisect a bug), and I agree that in this case it makes more sense to keep these images around.

Let me know what is your preference @mieubrisse

**Comment by mieubrisse** [comment]
Honestly I'm okay with the "keep ONLY the CLI version's images" case. This keeps Kurtosis as lean as possible for the user, and Kurtosians can just deal with re-pulling if they're bisecting a bug.

**Review by mieubrisse — APPROVED** [review]

**Pull request merged**
